### ISSUE TITLE
problem with installing dependencies

### ISSUE THREAD

**Issue by zez1998216** [bowang-lab/MedSAMSlicer#29] opened 2024-07-10 11:03 UTC
Hi, I used V1.0 and followed the Installation steps. However, after I clicked the 'Install dependencies' button, the state shown in the picture has lasted for more than 1 hour. Is that normal？What should I do?
![1720608759215](https://github.com/bowang-lab/MedSAMSlicer/assets/163626789/90d8016b-dbac-455b-8a2d-e8d9e42abf87)

**Comment by zez1998216** [comment] 2024-07-10 11:49
problem solved: keep waiting...

**Comment by LambdaLi** [comment] 2024-07-11 00:09
I don't even have a progress bar, the entire software is in an unresponsive state. Is there any other path to install these dependencies (environment)

**Comment by chovvvvvy** [comment] 2024-07-11 07:51
> 我甚至没有进度条，整个软件处于无响应状态。是否有其他路径可以安装这些依赖项（环境）

I am in the same situation, have you solved it yet?

**Comment by LambdaLi** [comment] 2024-07-11 07:58
> > 我甚至没有进度条，整个软件处于无响应状态。是否有其他路径可以安装这些依赖项（环境）
> 
> I am in the same situation, have you solved it yet?

Nope, I choose another segmentation software called "Pair" and it's free for 15 days which is enough for me to complete task. It only has the large model SAM inside (no MedSAM), but it's quite convenient for me.

**Comment by chovvvvvy** [comment] 2024-07-11 08:01
> > > 我甚至没有进度条，整个软件处于无响应状态。是否有其他路径可以安装这些依赖项（环境）
> > 
> > 
> > I am in the same situation, have you solved it yet?
> 
> Nope, I choose another segmentation software called "Pair" and it's free for 15 days which is enough for me to complete task. It only has the large model SAM inside (no MedSAM), but it's quite convenient for me.

Thank you very much for your reply.

**Comment by dzenanz** [comment] 2024-07-11 17:02
Pressing `Ctrl+0` to show the `Error log` should give you more information. You can also access it via `View` menu.

**Comment by dzenanz** [comment] 2024-07-11 17:03
I suspect that this issue is a duplicate of #28.

**Comment by Darius-Lbz** [comment] 2024-08-28 03:14
Traceback (most recent call last):
  File "E:/3D_Slicer_data/MedSAMSlicer-0.1/MedSAM/MedSAMLite/MedSAMLite.py", line 535, in install_dependencies
    self.installTorch(dependencies[dependency])
  File "E:/3D_Slicer_data/MedSAMSlicer-0.1/MedSAM/MedSAMLite/MedSAMLite.py", line 501, in installTorch
    if version.parse(torchLogic.torch.__version__) < version.parse(minTorch) or version.parse(torchLogic.torchvisionVersionInformation.split(' ')[-1]) < version.parse(minTorchVision):
  File "E:\3D_Slicer\Slicer 5.6.2\lib\Python\Lib\site-packages\packaging\version.py", line 54, in parse
    return Version(version)
  File "E:\3D_Slicer\Slicer 5.6.2\lib\Python\Lib\site-packages\packaging\version.py", line 200, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: 'installed'

**Comment by rasakereh** [comment] 2024-08-30 17:43
It seems that you have the wrong version of pytorch installed. beside the plugins drop-down menu there is a magnifier icon. click on it and look for PyTorch Utils. Uninstall the current versions and install `torch: 2.0.1 torchvision: 0.15.2`

**Closed** 2024-09-25 17:01 UTC
